{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-13846",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://github.com/hpcng/singularity/security/advisories/GHSA-6w7g-p4jh-rf92",
                    "name": "https://github.com/hpcng/singularity/security/advisories/GHSA-6w7g-p4jh-rf92",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://medium.com/sylabs",
                    "name": "https://medium.com/sylabs",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "Sylabs Singularity 3.5.0 through 3.5.3 fails to report an error in a Status Code."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-07-14T18:15Z",
    "lastModifiedDate": "2020-07-14T18:15Z"
}