{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-13692",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": [
                        {
                            "lang": "en",
                            "value": "CWE-611"
                        }
                    ]
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://github.com/pgjdbc/pgjdbc/commit/14b62aca4764d496813f55a43d050b017e01eb65",
                    "name": "https://github.com/pgjdbc/pgjdbc/commit/14b62aca4764d496813f55a43d050b017e01eb65",
                    "refsource": "CONFIRM",
                    "tags": [
                        "Patch",
                        "Third Party Advisory"
                    ]
                },
                {
                    "url": "https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.13",
                    "name": "https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.13",
                    "refsource": "CONFIRM",
                    "tags": [
                        "Release Notes",
                        "Third Party Advisory"
                    ]
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20200619-0005/",
                    "name": "https://security.netapp.com/advisory/ntap-20200619-0005/",
                    "refsource": "CONFIRM",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "PostgreSQL JDBC Driver (aka PgJDBC) before 42.2.13 allows XXE."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": [
            {
                "operator": "OR",
                "cpe_match": [
                    {
                        "vulnerable": true,
                        "cpe23Uri": "cpe:2.3:a:postgresql:postgresql_jdbc_driver:*:*:*:*:*:*:*:*",
                        "versionEndExcluding": "42.2.13"
                    }
                ]
            }
        ]
    },
    "impact": {
        "baseMetricV3": {
            "cvssV3": {
                "version": "3.1",
                "vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "attackVector": "NETWORK",
                "attackComplexity": "LOW",
                "privilegesRequired": "NONE",
                "userInteraction": "NONE",
                "scope": "UNCHANGED",
                "confidentialityImpact": "HIGH",
                "integrityImpact": "HIGH",
                "availabilityImpact": "HIGH",
                "baseScore": 9.8,
                "baseSeverity": "CRITICAL"
            },
            "exploitabilityScore": 3.9,
            "impactScore": 5.9
        },
        "baseMetricV2": {
            "cvssV2": {
                "version": "2.0",
                "vectorString": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
                "accessVector": "NETWORK",
                "accessComplexity": "LOW",
                "authentication": "NONE",
                "confidentialityImpact": "PARTIAL",
                "integrityImpact": "PARTIAL",
                "availabilityImpact": "PARTIAL",
                "baseScore": 7.5
            },
            "severity": "HIGH",
            "exploitabilityScore": 10.0,
            "impactScore": 6.4,
            "acInsufInfo": false,
            "obtainAllPrivilege": false,
            "obtainUserPrivilege": false,
            "obtainOtherPrivilege": false,
            "userInteractionRequired": false
        }
    },
    "publishedDate": "2020-06-04T16:15Z",
    "lastModifiedDate": "2020-06-19T11:15Z"
}