{
    "cve": {
        "data_type": "CVE",
        "data_format": "MITRE",
        "data_version": "4.0",
        "CVE_data_meta": {
            "ID": "CVE-2020-14149",
            "ASSIGNER": "cve@mitre.org"
        },
        "problemtype": {
            "problemtype_data": [
                {
                    "description": []
                }
            ]
        },
        "references": {
            "reference_data": [
                {
                    "url": "https://bugs.gentoo.org/726308",
                    "name": "https://bugs.gentoo.org/726308",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://github.com/troglobit/uftpd/issues/30",
                    "name": "https://github.com/troglobit/uftpd/issues/30",
                    "refsource": "MISC",
                    "tags": []
                },
                {
                    "url": "https://github.com/troglobit/uftpd/releases/tag/v2.12",
                    "name": "https://github.com/troglobit/uftpd/releases/tag/v2.12",
                    "refsource": "MISC",
                    "tags": []
                }
            ]
        },
        "description": {
            "description_data": [
                {
                    "lang": "en",
                    "value": "In uftpd before 2.12, handle_CWD in ftpcmd.c mishandled the path provided by the user, causing a NULL pointer dereference and denial of service, as demonstrated by a CWD /.. command."
                }
            ]
        }
    },
    "configurations": {
        "CVE_data_version": "4.0",
        "nodes": []
    },
    "impact": {},
    "publishedDate": "2020-06-15T18:15Z",
    "lastModifiedDate": "2020-06-15T18:19Z"
}